import Head from "next/head";
import {
  getAuth,
  signInWithEmailAndPassword,
  signInWithPopup,
} from "firebase/auth";
import { Input } from "@mantine/core";
import { useRouter } from "next/router";
import { useForm } from "react-hook-form";
import { CommonHeader } from "../../stories/components/CommonHeader";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { notify, signupmissnotify } from "../../stories/components/SiteModal";
import { CommonLabel } from "../../stories/components/CommonLabel";
import { CommonTitle } from "../../stories/components/CommonTitle";
import { CommonButton } from "../../stories/components/CommonButton";
import { CommonInput } from "../../stories/components/CommonInput";

export default function Login() {
  const { register, handleSubmit } = useForm();
  const router = useRouter();
  const auth = getAuth();

  const SignIn = (data: any) => {
    signInWithEmailAndPassword(auth, data.email, data.password)
      .then((userCredential: any) => {
        const user = userCredential.user;
        localStorage.setItem("Token", user.accessToken);
        notify("ログインできました");
        setTimeout(() => {
          router.push("/");
        }, 2000);
      })
      .catch((err) => {
        signupmissnotify("ログインできません");
        console.log(err);
      });
  };

  return (
    <>
      <Head>
        <title>出席管理</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <CommonHeader />
      <ToastContainer />
      <div className="max-w-4xl m-auto mt-10">
        <CommonTitle title="管理者ログイン" />
        <div>
          <form onSubmit={handleSubmit(SignIn)}>
            <div>
              <CommonLabel
                labelText="メールアドレス"
                required
                htmlfor="email"
              />
              <CommonInput type="email" id="email" register={register} />
            </div>

            <CommonLabel labelText="パスワード" required htmlfor="password" />
            <CommonInput type="password" id="password" register={register} />
            <div className="my-4 m-auto text-center">
              <CommonButton
                text="ログインする"
                classNameText="bg-blue-500 hover:bg-blue-700"
              />
            </div>
          </form>
        </div>
      </div>
    </>
  );
}
