import Head from "next/head";
import {
  getAuth,
  signInWithEmailAndPassword,
  signInWithPopup,
} from "firebase/auth";
import { Input } from "@mantine/core";
import { useRouter } from "next/router";
import { useForm } from "react-hook-form";
import { InputBase, Button } from "@mantine/core";
import { MuiNavbar } from "../../components/MuiNavbar";
import { ToastContainer, toast } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

export default function Login() {
  const { register, handleSubmit } = useForm();
  const router = useRouter();
  const auth = getAuth();

  const notify = () =>
    toast.success("ログインできました", {
      position: "top-center",
      autoClose: 5000,
      hideProgressBar: false,
      closeOnClick: true,
      pauseOnHover: true,
      draggable: true,
      progress: undefined,
      theme: "light",
    });

  const SignIn = (data: any) => {
    signInWithEmailAndPassword(auth, data.email, data.password)
      .then((userCredential: any) => {
        const user = userCredential.user;
        localStorage.setItem("Token", user.accessToken);
        notify();
        setTimeout(() => {
          router.push("/");
        }, 2000);
      })
      .catch((err) => {
        alert("ログインできません");
        console.log(err);
      });
  };

  return (
    <>
      <Head>
        <title>出席管理</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MuiNavbar />
      <ToastContainer />
      <div className="max-w-4xl m-auto mt-10">
        <h2 className="text-center">管理者ログイン</h2>

        <div>
          <form onSubmit={handleSubmit(SignIn)}>
            <div>
              <label htmlFor="email">メールアドレス</label>
              <Input type="email" id="email" {...register("email")} />
            </div>

            <label htmlFor="password">パスワード</label>
            <Input type="password" id="password" {...register("password")} />
            <div className="my-4 m-auto text-center">
              <Button type="submit" variant="outline" color="cyan">
                ログインする
              </Button>
            </div>
          </form>
        </div>
      </div>
    </>
  );
}
