import Head from "next/head";
import { Input } from "@mantine/core";
import { database } from "../../firebaseConfig";
import { collection, addDoc } from "firebase/firestore";
import { useRouter } from "next/router";
import { useForm } from "react-hook-form";
import { Button } from "@mantine/core";
import { InputBase } from "@mantine/core";
import { CommonHeader } from "../../stories/components/CommonHeader";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import { notify, signupmissnotify } from "../../stories/components/SiteModal";

export default function Home() {
  const { register, handleSubmit } = useForm();
  const router = useRouter();
  const usersRef = collection(database, "users");
  //新しい順
  const addDate = (data: any) => {
    const newdate = new Date().toLocaleString("ja-JP");
    //日本時間を代入
    //写真のurlをセットする
    addDoc(usersRef, {
      fullname: data.fullname,
      univernumber: data.univernumber,
      grade: data.grade,
      createtime: newdate,
      gender: data.gender,
      belong: "在籍中",
      attend: 0,
    })
      .then(() => {
        notify("ユーザー登録しました");
        setTimeout(() => {
          router.push("/");
        }, 2000);
      })
      .catch((err: any) => {
        signupmissnotify("ユーザー登録に失敗しました");
        console.error(err);
      });
  };

  return (
    <>
      <Head>
        <title>出席管理</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <CommonHeader />
      <ToastContainer />
      <div className="max-w-5xl m-auto">
        <h2 className="text-center text-2xl font-bold mb-6 mt-10">
          ユーザーを登録する
        </h2>

        <div>
          <form onSubmit={handleSubmit(addDate)}>
            <div>
              <label htmlFor="fullname">名前</label>
              <Input type="text" id="fullname" {...register("fullname")} />
            </div>
            <div>
              <label htmlFor="univernumber">学籍番号</label>
              <Input
                type="text"
                id="univernumber"
                {...register("univernumber")}
              />
              <InputBase
                label="性別"
                component="select"
                mt="md"
                id="gender"
                {...register("gender")}
              >
                <option value="男性">男性</option>
                <option value="女性">女性</option>
                <option value="非公開">非公開</option>
              </InputBase>

              <InputBase
                label="年度"
                component="select"
                mt="md"
                id="grade"
                {...register("grade")}
              >
                <option value="インターン">インターン</option>
                <option value="1年目">1年目</option>
                <option value="2年目">2年目</option>
                <option value="アドバイザー">アドバイザー</option>
              </InputBase>
            </div>
            <div className="my-4 text-center">
              <Button type="submit" variant="outline" color="cyan">
                登録する
              </Button>
            </div>
          </form>
        </div>
      </div>
    </>
  );
}
