import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";

import { useState, useEffect } from "react";
import { database } from "../firebaseConfig";
import { collection, addDoc, onSnapshot } from "firebase/firestore";
import { useRouter } from "next/router";
import { query, orderBy } from "firebase/firestore";
import { useForm } from "react-hook-form";

import {
  createStyles,
  Table,
  Checkbox,
  ScrollArea,
  Group,
  Avatar,
  Text,
} from "@mantine/core";

export default function Home() {
  const { register, handleSubmit } = useForm();
  const [title, setTitle] = useState("");
  const [users, setUsers] = useState<any[]>([]);
  const databaseRef = collection(database, "meeting");
  const router = useRouter();
  const usersRef = collection(database, "users");
  //新しい順
  const q = query(usersRef, orderBy("timestamp", "desc"));

  const addDate = (data: any) => {
    const newdate = new Date().toLocaleString("ja-JP");
    //日本時間を代入
    //写真のurlをセットする
    addDoc(databaseRef, {
      title: data.univernumber,
      createtime: newdate,
    })
      .then(() => {
        alert("a");
        router.push("/");
      })
      .catch((err: any) => {
        console.error(err);
      });
  };

  // 新着順…
  const getallUsers = () => {
    onSnapshot(q, (querySnapshot) => {
      setUsers(
        querySnapshot.docs.map((doc) => ({ ...doc.data(), id: doc.id }))
      );
      console.log(users);
    });
  };

  useEffect(() => {
    getallUsers();
  }, []);

  return (
    <>
      <Head>
        <title>出席管理</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="">
        <h2>今日のmeeting</h2>

        <ScrollArea>
          <Table sx={{ minWidth: 800 }} verticalSpacing="sm">
            <thead>
              <tr>
                <th style={{ width: 40 }}></th>
                <th>名前</th>
                <th>学籍番号</th>
                <th>年次</th>
              </tr>
            </thead>
            <tbody>
              <tr key="1">
                <td>
                  <Checkbox transitionDuration={0} />
                </td>
                <td>
                  <Group spacing="sm">
                    {/* <Avatar size={26} src={item.avatar} radius={26} /> */}
                    <Text size="sm" weight={500}>
                      aa
                    </Text>
                  </Group>
                </td>
                <td>a</td>
                <td>a</td>
              </tr>
            </tbody>
          </Table>
        </ScrollArea>

        <div>
          <h2>北星ピア・サポーター</h2>
          <p>おはようございます。</p>
          <form onSubmit={handleSubmit(addDate)}>
            <p>
              <label htmlFor="univernumber">学籍番号</label>
              <input
                type="number"
                id="univernumber"
                {...register("univernumber")}
              />
            </p>
            <button type="submit">送信</button>
          </form>
        </div>
      </div>
    </>
  );
}
